### ISSUE TITLE
Limitations

### ISSUE THREAD

**Issue by awarbler** [byui-cse397/2024WinCSE490PCP#107]
I wont add these issues until we discuss as a team 

- [x] Hardware Limitations
- [x] Interfaces to other applications
- [x] Parallel Operatons
- [x] Audit Functions
- [x] Control Functions
- [x] Higher order language requirements
- [x] Signal Handshake Protocols
- [x] Quality Requirements
- [x] Criticality of the Application
- [x] Safety and security considerations
- [x] Physical / Mental Considerations usually NA
